version: '2.1'
services:
   db:
      image: postgres:9.5
      container_name: "db"
      hostname: "db"
      ports:
       - "5432:5432"
      environment:
       - POSTGRES_USER=holmes
       - POSTGRES_PASSWORD=holmespwd

   consul:
      image: consul:0.8.3
      container_name: "consul"
      hostname: "consul"
      ports:
       - "8400:8400"
       - "8500:8500"
       - "8600:8600"
      command: "agent -server -bootstrap-expect 1 -client 0.0.0.0"

   config_binding_service:
      image: {{ nexus_docker_repo }}/onap/org.onap.dcaegen2.platform.configbinding:v1.2.0
      container_name: "config_binding_service"
      hostname: "config_binding_service"
      environment:
       - CONSUL_HOST="consul"
      ports:
       - "10000:10000"
      depends_on:
       - consul

