version: '2.1'
services:
   snmptrap:
      image: "{{ nexus_docker_repo}}/onap/org.onap.dcaegen2.collectors.snmptrap:{{ dcae_docker_snmptrap }}"
      container_name: "static-dcaegen2-collectors-snmptrap"
      restart: "always"
      hostname: "static-dcaegen2-collectors-snmptrap"
      environment:
       - "DMAAPHOST={{ mr_ip_addr }}"
       - "CONSUL_HOST=consul"
       - "CONSUL_PORT=8500"
       - "CONFIG_BINDING_SERVICE=config_binding_service"
       - "SERVICE_NAME=static-dcaegen2-collectors-snmptrap"
       - "HOSTNAME=static-dcaegen2-collectors-snmptrap"
       - "HOSTALIASES=/etc/host.aliases"
      ports:
       - "162:6162/udp"
      labels:
       - "SERVICE_NAME=static-dcaegen2-collectors-snmptrap"
       - "SERVICE_CHECK_DOCKER_SCRIPT=/opt/app/snmptrap/bin/healthcheck.sh"
       - "SERVICE_CHECK_INTERVAL=15s"
       - "SERVICE_CHECK_INITIAL_STATUS=passing"

